### ISSUE TITLE
Entity name for sheep

### ISSUE THREAD

**Issue by MrKashew** [Rin-chan/MoreWoolMod#1]
Bit of a nit - entity name does not show so well for mods such as Jade, Neat, and minimap (Xaero) - here is a screenshot showing all 3 being displayed
![2023-07-05_20 54 21](https://github.com/Rin-chan/MoreWoolMod/assets/53996665/6cd3175e-03fb-4dd5-987b-4a73426f6c0f)

**Comment by Rin-chan** [comment]
Should be fixed now. Thanks for pointing it out!
